# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kanna_03' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kanna', '~> 5.0.0'
  # Pods for kanna_03

  target 'kanna_03Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kanna_03UITests' do
    # Pods for testing
  end

end
